check_for_binary_files_without_source_code:
  comment: 'Added binary file declaration in README.txt.'
check_for_plain_text_credentials_in_python:
  comment: 'Verified'
check_for_secret_disclosure:
  comment: 'Secrets/passwords are not disclosed in any of the files.'
check_for_builtin_functions:
  comment: 'Verified'
check_for_importing_modules:
  comment: 'Verified'
check_for_data_compression_and_archiving:
  comment: 'Verified'
check_for_executable_flag:
  comment: 'Verified'
check_for_file_and_directory_access:
  comment: 'Verified'
check_built_in_import_function:
  comment: 'Verified'
check_for_environment_variable_use_in_python:
  comment: 'Verified'
check_for_generic_operating_system_services:
  comment: 'Verified'
